### ISSUE TITLE
 gerrit plugins crash when try to download 

### ISSUE THREAD

**Issue by lintaonz** [gitextensions/GitExtensions.GerritPlugin#5]
Here is my .gitreview

```
[gerrit]
host=localhost
port=29418
project=project.git
defaultbranch=master
defaultremote=master
defaultrebase=0
```

I can upload my commit to gerrit without issue.

But when I click the download button, it show up a screen with follow fields:

Remote: origin
Change (Enter the Change-Id or the number from the Gerrit URL):
Topic branch:

I input my change-id 1110 and leave Topic branch as blank then click 'download'. GitExtensions just crash.

Cheers,

**Comment by thimmy687** [comment]
Hi,
it looks like that this feature is already implemented here:
https://github.com/gitextensions/gitextensions/commit/2329ae3262001b8597828670d334259bf36671ea

Maybe I could change if the result is null, I raise an error, that SSH was not found and the user need to install it or setup OpenSHH in the settings?

Or we need to check if the implementation is buggy in GE.

**Comment by thimmy687** [comment]
Today I read that OpenSSH is installed by default on windows 10 since 1809.

Should we close this issue?

**Comment by RussKie** [comment]
Our telemetry based on 430K sessions from 2,800 opted in users in the last 90 days shows the following:

OS | Count | Percentage
--|---|--
Windows 10.0.18363 | 163425 | 37.93%
Windows 10.0.19041 | 78891 | 18.31%
Windows 10.0.19042 | 65888 | 15.29%
Windows 10.0.17763 | 52378 | 12.16%
Windows 10.0.16299 | 14021 | 3.25%
Windows 10.0.18362 | 12057 | 2.80%
Windows 10.0.17134 | 11223 | 2.60%
Windows 6.2.9200 | 9225 | 2.14%
Windows 6.1.7601 | 8959 | 2.08%
Windows 10.0.14393 | 7314 | 1.70%
Windows 6.3.9600 | 4834 | 1.12%
Windows 10.0.(other) | 2655 | 0.61%

Interpolating from our download counters, we have a substantial number of users who still use older versions of Windows. However it is totally unknown how many of those users use the plugin.

I totally have no opinion either way since I a) don't use gerrit, and b) on the latest(ish) Windows 10 version.
However given the age of the issue and absence of incoming fixes, it is totally reasonable to assume the plugin users aren't totally blocked by this issue.

Thank you @thimmy687 for looking into it.
